"""
Constants for DasTrader Dashboard
"""
# CMD API Response Markers
MARKER_POS_START = "#POS"
MARKER_POS_END = "#POSEND"
MARKER_ORDER_START = "#Order"
MARKER_ORDER_END = "#OrderEnd"
MARKER_TRADE_START = "#Trade"
MARKER_TRADE_END = "#TradeEnd"
MARKER_SLORDER_START = "#SLOrder"
MARKER_SLORDER_END = "#SLOrderEnd"

# Position Types
POS_TYPE_CASH = "1"
POS_TYPE_MARGIN = "2"
POS_TYPE_SHORT = "3"

# Order Status
ORDER_STATUS_CLOSED = "Closed"
ORDER_STATUS_HOLD = "Hold"
ORDER_STATUS_SENDING = "Sending"
ORDER_STATUS_ACCEPTED = "Accepted"
ORDER_STATUS_CANCELED = "Canceled"
ORDER_STATUS_REJECTED = "Rejected"
ORDER_STATUS_EXECUTED = "Executed"
ORDER_STATUS_PARTIAL = "Partial"
ORDER_STATUS_TRIGGERED = "Triggered"

# Order Sides
ORDER_SIDE_BUY = "B"
ORDER_SIDE_SELL = "S"
ORDER_SIDE_SHORT = "SS"
ORDER_SIDE_BUY_OPEN = "BO"
ORDER_SIDE_BUY_CLOSE = "BC"
ORDER_SIDE_SELL_OPEN = "SO"
ORDER_SIDE_SELL_CLOSE = "SC"

# Update intervals (in seconds)
POSITION_UPDATE_INTERVAL = 1
ORDER_UPDATE_INTERVAL = 1
TRADE_UPDATE_INTERVAL = 1
ACCOUNT_UPDATE_INTERVAL = 5

